github: [Niyomugabo-fred]
patreon: niyomugabo
open_collective: lightmgroup
ko_fi: frederic_niyomugabo
tidelift: npm/luminajs
community_bridge: luminajs
liberapay: niyomugabo
issuehunt: luminajs
lfx_crowdfunding: luminajs
polar: niyomugabo
buy_me_a_coffee: frederic
thanks_dev: niyomugabo
custom: ['https://lightmgroup.com/donate', 'https://paypal.me/NiyomugaboFrederic']
